services:
  web:
    build: .
    ports:
      - "9400:80"
    volumes:
      - ./core/env.py:/app/core/env.py
    restart: "always"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G

