DEBUG = False
DISABLE_ADMIN = True
SECRET_KEY = "NODE_SECRET_KEY"
POSTGRES_PASSWORD = "NODE_DB_PASS"
POSTGRES_HOST = "NODE_DB_HOST"
POSTGRES_PORT = "NODE_DB_PORT"

LIMIT_DISK = "CH_LIMIT_DISK"

S3_ACCESS_KEY = "NODE_S3_ACCESS_KEY"
S3_SECRET_KEY = "NODE_S3_SECRET_KEY"
S3_ENDPOINT_URL = "https://NODE_S3_ENDPOINT_URL"

S3_NEW_ACCESS_KEY = "NODE_S3_NEW_ACCESS_KEY"
S3_NEW_SECRET_KEY = "NODE_S3_NEW_SECRET_KEY"
S3_NEW_ENDPOINT_URL = "https://NODE_S3_NEW_ENDPOINT_URL"

S3_ACCESS_KEY_LAST_BACKUP = "NODE_S3_ACCESS_KEY_LAST_BACKUP"
S3_SECRET_KEY_LAST_BACKUP = "NODE_S3_SECRET_KEY_LAST_BACKUP"
S3_ENDPOINT_URL_LAST_BACKUP = "https://NODE_S3_ENDPOINT_URL_LAST_BACKUP"

NODE_IP = "SERVER_NAME"
PROXY_IPS = "SERVER_NAME"
NODE_NAME = "CH_NODE_NAME"
